#!/bin/bash

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
export PATH

case "$1" in
	start)
		/usr/local/bin/pgpool -d -n 2>&1 | /usr/sbin/rotatelogs  -l -f /var/log/pgpool/pgpool.log.%A 86400 &
		exit $?
	;;
	stop)
		/usr/local/bin/pgpool $2 $3 stop 
	;;
	status)
		cat /var/run/pgpool/pgpool.pid 2> /dev/null
		if [ $? -eq 1 ]; then
			echo "pgpool is not running"
		else
			echo ": pgpool is working"
		fi					
	;;
	add)
		/usr/local/bin/pcp_attach_node 2 `uname -n` 9898 postgres postgres $2
	;;
        del)
                /usr/local/bin/pcp_detach_node 2 `uname -n` 9898 postgres postgres $2
        ;;
        *)
	echo "Usage: $0 {start|stop|status|add|del} [-m fast|nodenum]"
	exit 7
esac

exit 0
